-- This script is converted with PtokaX LUA API Converter v0.9 at 03/23/08 15:34:37

-- TrickerBot2.lua, created by Ptaczek Dec-24, 2002 --
-- Talkingbot for Ptokax by Troubadour 13 june 2003 --
-- Translated by [NL]MrBuitenhuizen --
-- Some fixes by DJ Bert 11 march 2004 --
-- Rewritten to lua 5 by DJ Bert 15 April 2005 --
-- Fixed answer from bot after usercommands by DJ Bert (Help needed by HAWK) 15 May 2005 --
-- 2 different triggerbots made as 1 bot by DJ Bert 18 May 2005 --
-- Added more trigs by DJ Bert 18 May 2005 --
-- Added random for trigs by DJ Bert 18 May 2005 --
-- Fixed the trigs part by DJ Bert 18 May 2005 --
-- Fixed command say and quiet by DJ Bert 30 May 2005 --
-- Replaced say & quiet with this:
-- !praataan -- start chatter
-- !praatuit -- stop chatter
-- Added a right click On/Off by Shuckie
-- 2014-10-12
-- Converted to luadch by Jerker/Kungen
-- Removed right click by Jerker/Kungen

local scriptname = "ptx_rotatingtopic"
local scriptversion = "0.1"

local BotName	 = "[--=Mr.Fun=--]"
local hubname	 = "adcs://your.hubaddress.org:port"


local idlequestions = {
"\r\n\r\n                   ..........A clear conscience is usually a sign of a bad memory..........\r\n",
"\r\n\r\n                   ..........Someone be nice to you but rude to the waiter, is not a nice person..........\r\n",
"\r\n\r\n                   ..........I'm not SMALL I'm just funsized..........\r\n",
"\r\n\r\n                   ..........I'll try being nicer if you'll try being smarter..........\r\n",
"\r\n\r\n                   ..........I know I'm not perfect, and I DON'T claim to be!..........\r\n",
"\r\n\r\n                   ..........Don't worry. I forgot your name too..........\r\n",
"\r\n\r\n                   ..........I'm really easy to get along with once you people learn to worship me..........\r\n",
"\r\n\r\n                   ..........Den som inte tror att man kan bli berusad på vatten har aldrig åkt Finlandsfärja..........\r\n",
"\r\n\r\n                   ..........How can I miss you if you won't go away?..........\r\n",
"\r\n\r\n                   ..........BTW, A hard on doesn't count as personal growth..........\r\n",
"\r\n\r\n                   ..........Don't you need a license to be that ugly?..........\r\n",
"\r\n\r\n                   ..........Dont take life seriously no one gets out alive anyways..........\r\n",
"\r\n\r\n                   ..........I used up all my sick days, so I called in dead..........\r\n",
"\r\n\r\n                   ..........Cheating is not bad, it's just teamwork..........\r\n",
"\r\n\r\n                   ..........I want to be your favourite hello and your most difficult goodbye..........\r\n",
"\r\n\r\n                   ..........I just added YOU to my TO-DO list!..........\r\n",
"\r\n\r\n                   ..........Aliens are real, they're just afraid of Chuck Norris..........\r\n",
"\r\n\r\n                   ..........Only good girls can be naughty..........\r\n",
"\r\n\r\n                   ..........Everything goes with fitting and measuring; if you do not measure, it does not fit, and if it does not fit, you must measure..........\r\n",
"\r\n\r\n                   ..........Everything has its beauty but not everyone sees it..........\r\n",
"\r\n\r\n                   ..........If the only place I could see you was in my dreams, I would sleep forever..........\r\n",
"\r\n\r\n                   .......... 9 out of 10 voices in my head agree that I'm sane..........\r\n",
"\r\n\r\n                   ..........Who is that? I think it was Bruce Willis..........\r\n",
"\r\n\r\n                   ..........If the taxi driver reverse, should he pay you..........\r\n",
"\r\n\r\n                   ..........I just added YOU to my TO-DO list!..........\r\n",
"\r\n\r\n                   ..........If doping is forbidden for athletes, Photoshop would not be banned for models..........\r\n",
"\r\n\r\n                   ..........When a man cleaning something, he always makes something dirty..........\r\n",
"\r\n\r\n                   ..........When a newly married man looks happy, we understand why..........\r\n",
"\r\n\r\n                   ..........If a star is so far away, how can you then come so close..........\r\n",
"\r\n\r\n                   ..........If a woman says that you go too far, you come too close to..........\r\n",
"\r\n\r\n                   ..........If a job is worth doing, then that's worth doing well..........\r\n",
"\r\n\r\n                   ..........I didn't trip. I just said hello to the wall, with my face!..........\r\n",
"\r\n\r\n                   ..........Everyone is entitled to my opinion..........\r\n",
"\r\n\r\n                   ..........Backwards compatible' means: 'if it isn't backwards, it's not compatible..........\r\n",
"\r\n\r\n                   ..........CAUTION! I will spank you and you will like it!..........\r\n",
"\r\n\r\n                   ..........Back up my hard drive? And what, run over something?..........\r\n",
"\r\n\r\n                   ..........I just added YOU to my TO-DO list!..........\r\n",
"\r\n\r\n                   ..........If it were up to men ... People did not talk about their emotions..........\r\n",
"\r\n\r\n                   ..........I wasn't sleeping. I was testing the keyboard for drool resistance..........\r\n",
"\r\n\r\n                   ..........not the sharpest tool in the box are ya?'..........\r\n",
"\r\n\r\n                   ..........Been there, Done that, Got the t-shirt!..........\r\n",
"\r\n\r\n                   ..........Clones are people two..........\r\n",
"\r\n\r\n                   ..........The guy who discovered milk....What was he doing with that cow?..........\r\n",
"\r\n\r\n                   ..........If loving you was a crime, I am now the most wanted criminal..........\r\n",
"\r\n\r\n                   ..........If everyone wants to play the first violin you never get a band together..........\r\n",
"\r\n\r\n                   ..........Beware of the toes you step on today, they may be connected to the foot up your ass tomorrow..........\r\n",
"\r\n\r\n                   ..........BTW, a hard on doesn't count as personal growth..........\r\n",
"\r\n\r\n                   ..........Build a system that even a fool can use, and only a fool will want to use it..........\r\n",
"\r\n\r\n                   ..........By the time you can make ends meet, they move the ends..........\r\n",
"\r\n\r\n                   ..........CAUTION! Extremely horny and easily excitable...proceed with caution..........\r\n",
"\r\n\r\n                   ..........CAUTION! I will spank you and you will like it..........\r\n",
"\r\n\r\n                   ..........Change is inevitable, except from vending machines..........\r\n",
"\r\n\r\n                   ..........Click your heels together 3 times and go fuck yourself..........\r\n",
"\r\n\r\n                   ..........Clothing is OPTIONAL beyond this point..........\r\n",
"\r\n\r\n                   ..........Common sense, so rare it's a super power..........\r\n",
"\r\n\r\n                   ..........Confidence.. Wear it like make-up..........\r\n",
"\r\n\r\n                   ..........Damn baby, talk nerdy to me..........\r\n",
"\r\n\r\n                   ..........Damn the things I could do to you if you were in my presense...mmmmmm..........\r\n",
"\r\n\r\n                   ..........Dear Santa, Can I have the numbers of the boys on the naughty list..........\r\n",
"\r\n\r\n                   ..........Depression is merely anger without enthusiasm..........\r\n",
"\r\n\r\n                   ..........Did you eated my cookie??? But why..........\r\n",
"\r\n\r\n                   ..........Dip me in horny and throw me to the lesbians..........\r\n",
"\r\n\r\n                   ..........Distance means so little when someone means soo much..........\r\n",
"\r\n\r\n                   ..........Don't be fooled. I don't care..........\r\n",
"\r\n\r\n                   ..........Don't let your past, determine your destiny..........\r\n",
"\r\n\r\n                   ..........Don't stick your tounge out, UNLESS you plant to use it..........\r\n",
"\r\n\r\n                   ..........Don't use big words unless you know what they mean..........\r\n",
"\r\n\r\n                   ..........Don't worry about what people think, they Don't do it very often..........\r\n",
"\r\n\r\n                   ..........Dont like me? Mind over matter. I dont mind and you don't matter..........\r\n",
"\r\n\r\n                   ..........Dont take life seriously no one gets out alive anyways..........\r\n",
"\r\n\r\n                   ..........Drunken words are sober thoughts..........\r\n",
"\r\n\r\n                   ..........Eagles may soar, but weasels don't get sucked into jet engines..........\r\n",
"\r\n\r\n                   ..........Eat well, stay fit, die anyway..........\r\n",
"\r\n\r\n                   ..........Evil needs candy too..........\r\n",
"\r\n\r\n                   ..........Experience is a wonderful thing. It enables you to recognize a mistake when you make it again..........\r\n",
"\r\n\r\n                   ..........Face it! You love me..........\r\n",
"\r\n\r\n                   ..........FEDSEX when u absolutely have to get it overnight..........\r\n",
"\r\n\r\n                   ..........FLASH ME! I'm bored..........\r\n",
"\r\n\r\n                   ..........For every action, there is an equal and opposite government program..........\r\n",
"\r\n\r\n                   ..........FREE HOT DOG! Bring me your buns..........\r\n",
"\r\n\r\n                   ..........Friends are like BRAS, Close to the heart and always there for support..........\r\n",
"\r\n\r\n                   ..........Friends ask what's wrong and say ok. Best friends say SHE'S PISSED!! MOVE..........\r\n",
"\r\n\r\n                   ..........Friends don't let friends do silly things...... ALONE..........\r\n",
"\r\n\r\n                   ..........GET NAKED! I have a plan..........\r\n",
"\r\n\r\n                   ..........Going to church doesn't make you a Christian anymore than standing in a garage makes you a car..........\r\n",
"\r\n\r\n                   ..........GOT ENEMIES? Good, means you've stood up for something..........\r\n",
"\r\n\r\n                   ..........GOT ME? I'll do your body good..........\r\n",
"\r\n\r\n                   ..........Hallo Matt Demon, is Yes-r..........\r\n",
"\r\n\r\n                   ..........Hard work pays off in the future. Laziness pays off now..........\r\n",
"\r\n\r\n                   ..........Have you ever noticed that anybody driving slower than you is an idiot, and anyone going faster than y ou is a maniac..........\r\n",
"\r\n\r\n                   ..........He who laughs last, thinks slowest..........\r\n",
"\r\n\r\n                   ..........Hey...HEY, I can't make excuses if you're not paying attention..........\r\n",
"\r\n\r\n                   ..........How about never? Is never good for you..........\r\n",
"\r\n\r\n                   ..........How many of you believe in psycho-kinesis? Raise my hand..........\r\n",
"\r\n\r\n                   ..........How much deeper would the ocean be without sponges..........\r\n",
"\r\n\r\n                   ..........How nice of you to take this time to humiliate yourself in public..........\r\n",
"\r\n\r\n                   ..........I'll pick you up when you fall, and if I can't I'll lie down beside you..........\r\n",
"\r\n\r\n                   ..........I'll try being nicer if you'll try being smarter..........\r\n",
"\r\n\r\n                   ..........I'm a bad influence, but DAMN I'm fun..........\r\n",
"\r\n\r\n                   ..........I'm a good girl, with A LOT of bad habits..........\r\n",
"\r\n\r\n                   ..........I'm already visualizing the duct tape over your mouth..........\r\n",
"\r\n\r\n                   ..........I'm confused...wait..maybe I'm not..........\r\n",
"\r\n\r\n                   ..........I'm definatly not perfect, but I am ALWAYS me..........\r\n",
"\r\n\r\n                   ..........I'm not a stalker. I'm just curious. Oh BTW you're out of milk..........\r\n",
"\r\n\r\n                   ..........I'm not being rude. you're just insignificant..........\r\n",
"\r\n\r\n                   ..........I'm not condescending,Im busy thinking bout things you wouldnt understand..........\r\n",
"\r\n\r\n                   ..........I'm not CRAZY! I just don't give a FUCK..........\r\n",
"\r\n\r\n                   ..........I'm not Evil! I'm angelically challenged..........\r\n",
"\r\n\r\n                   ..........I'M NOT FUCKING STUPID,.but I used to be..........\r\n",
"\r\n\r\n                   ..........I'm not mean, you're just a sissy..........\r\n",
"\r\n\r\n                   ..........I'm not SMALL I'm just funsized..........\r\n",
"\r\n\r\n                   ..........I'm probably the coolest DORK you'll ever meet..........\r\n",
"\r\n\r\n                   ..........I'm smiling because I have absolutely no idea what's going on..........\r\n",
"\r\n\r\n                   ..........I'm smiling, because they haven't found the bodies yet..........\r\n",
"\r\n\r\n                   ..........I'm Smiling...that alone should scare you..........\r\n",
"\r\n\r\n                   ..........I'm still young, I've got plenty more girls to see, and many more boys to piss off..........\r\n",
"\r\n\r\n                   ..........I'm the type of girl that's seen all horror movies but jumps when the toast pops up..........\r\n",
"\r\n\r\n                   ..........I'm the type of girl that will burst out laughing at something that happened yesterday..........\r\n",
"\r\n\r\n                   ..........I'm the type of person that walks into chairs and says sorry..........\r\n",
"\r\n\r\n                   ..........I'm through with love, thank fuck there's still sex..........\r\n",
"\r\n\r\n                   ..........I'm wearing no socks, and matching undies..........\r\n",
"\r\n\r\n                   ..........I'm weird but I'm saving up for eccentric..........\r\n",
"\r\n\r\n                   ..........I'm weird? Yeah I haven't heard that one before..........\r\n",
"\r\n\r\n                   ..........I became insane because of long intervals of sanity..........\r\n",
"\r\n\r\n                   ..........I can't promise to stove all your problems, but I can promise you won't have to face them alone..........\r\n",
"\r\n\r\n                   ..........I can see your point, but I still think you're full of shit..........\r\n",
"\r\n\r\n                   ..........I didn't do it. Nobody saw me. You can't prove a thing..........\r\n",
"\r\n\r\n                   ..........I didn't slap you! I simply High-Fived your face..........\r\n",
"\r\n\r\n                   ..........I didnt trip. I just said hello to the wall, with my face..........\r\n",
"\r\n\r\n                   ..........I do bad things... and I do them VERY VERY well..........\r\n",
"\r\n\r\n                   ..........I Don't know what your problem is, but I bet it's hard to pronounce..........\r\n",
"\r\n\r\n                   ..........I don't respond well to authority..........\r\n",
"\r\n\r\n                   ..........I dont need sex, life fucks me whenever it can..........\r\n",
"\r\n\r\n                   ..........I have plenty of talent and vision. I just Don't give a damn..........\r\n",
"\r\n\r\n                   ..........I haven't been this excited since my pager got stuck on vibrate..........\r\n",
"\r\n\r\n                   ..........I just added YOU to my TO-DO list..........\r\n",
"\r\n\r\n                   ..........I know I'm nice, but don't push my buttons..........\r\n",
"\r\n\r\n                   ..........I know Im not perfect, and I DONT claim to be..........\r\n",
"\r\n\r\n                   ..........I know nothing about sex... Can you teach me..........\r\n",
"\r\n\r\n                   ..........I like you.. You remind me of when I was young and stupid..........\r\n",
"\r\n\r\n                   ..........I love this retard I call my best friend..........\r\n",
"\r\n\r\n                   ..........I may be Evil, but atleast I'm cute while I'm doing it..........\r\n",
"\r\n\r\n                   ..........I see you've set aside this special time to humiliate yourself in public..........\r\n",
"\r\n\r\n                   ..........I speak my mind because it hurts to bite my tounge..........\r\n",
"\r\n\r\n                   ..........I tried setting my hotmail password to penis. It said my password wasn't long enough..........\r\n",
"\r\n\r\n                   ..........I tried to change my password to Penis but it wasn't long enough..........\r\n",
"\r\n\r\n                   ..........I used to think drinking was bad for me...so I stopped thinking..........\r\n",
"\r\n\r\n                   ..........I want to be your favourite hello and your most difficult goodbye..........\r\n",
"\r\n\r\n                   ..........I will always cherish the initial misconceptions I had about you..........\r\n",
"\r\n\r\n                   ..........If at first you don't succeed... DESTROY all evidence you tried..........\r\n",
"\r\n\r\n                   ..........If being sexy was a crime, you'd be guilty as charged..........\r\n",
"\r\n\r\n                   ..........If Drinking & Driving is illegal, then why do bars have parking lots..........\r\n",
"\r\n\r\n                   ..........If he's dumb enough to walk away, be smart enough to let him go..........\r\n",
"\r\n\r\n                   ..........If I shoot you, will you leave..........\r\n",
"\r\n\r\n                   ..........If I was any happier, I'd pass out..........\r\n",
"\r\n\r\n                   ..........If it has Tires or Testicles, it's gonna give you problems..........\r\n",
"\r\n\r\n                   ..........If it weren't for the gutter my mind would be homeless..........\r\n",
"\r\n\r\n                   ..........If the house was burning my friends would sit, make smores and hit on firemen..........\r\n",
"\r\n\r\n                   ..........If you're going to ride my ass the least you could do is pull my hair..........\r\n",
"\r\n\r\n                   ..........If you can't beat them, then ARRANGE to have them beaten..........\r\n",
"\r\n\r\n                   ..........If you can't laugh at yourself... I'll be glad to do it for you..........\r\n",
"\r\n\r\n                   ..........If you look like your passport picture, you probably need the trip..........\r\n",
"\r\n\r\n                   ..........If you must choose between two evils, pick the one you've never tried before..........\r\n",
"\r\n\r\n                   ..........If you really want to do something you'll find a way, if you don't, you'll find and excuse..........\r\n",
"\r\n\r\n                   ..........If you see CUPID, do me a favor and bitch slap that little punk will ya..........\r\n",
"\r\n\r\n                   ..........If you think Im always saying inappropriate things, imagine the things I keep to myself..........\r\n",
"\r\n\r\n                   ..........If you think nobody cares, try missing a couple of payments..........\r\n",
"\r\n\r\n                   ..........If you try to fail, and succeed, which have you done..........\r\n",
"\r\n\r\n                   ..........If you were my homework, I'd do you EVERY NIGHT..........\r\n",
"\r\n\r\n                   ..........IN CASE OF EMERGENCY- Run like hell..........\r\n",
"\r\n\r\n                   ..........In order to be Irreplacable, one must ALWAYS be different..........\r\n",
"\r\n\r\n                   ..........In three words I can sum up everything Ive learned about life... it goes on..........\r\n",
"\r\n\r\n                   ..........Individualism- Only losers listen to the input of others around them..........\r\n",
"\r\n\r\n                   ..........Insanity IS hereditary. You get it from your kids..........\r\n",
"\r\n\r\n                   ..........Inside every older person is a younger person wondering, What the heck happened..........\r\n",
"\r\n\r\n                   ..........It's a beautiful day, now watch some asshole fuck it up..........\r\n",
"\r\n\r\n                   ..........It's a good day when the shit flies and I have time to duck..........\r\n",
"\r\n\r\n                   ..........It's a thankless job, but I've got a lot of Karma to burn off..........\r\n",
"\r\n\r\n                   ..........It's funny...they gave me a jacket so I can hug myself..........\r\n",
"\r\n\r\n                   ..........It's not about who is real to your face, its about who stays real behind your back..........\r\n",
"\r\n\r\n                   ..........It's not ADHD It's random multi tasking..........\r\n",
"\r\n\r\n                   ..........It's not rape if you say SURPRISE..........\r\n",
"\r\n\r\n                   ..........It's okay, we're thinking WTF too..........\r\n",
"\r\n\r\n                   ..........It ain't the jeans that make your butt look fat..........\r\n",
"\r\n\r\n                   ..........It sounds like English, but I can't understand a word you're saying..........\r\n",
"\r\n\r\n                   ..........Junk is something you've kept for years and throw away three weeks before you need it..........\r\n",
"\r\n\r\n                   ..........Just have fun, and forget those who dont..........\r\n",
"\r\n\r\n                   ..........Just remember - if the world didn't suck, we would all fall off..........\r\n",
"\r\n\r\n                   ..........Learn from yesterday, Life for today, Hope for tomorrow..........\r\n",
"\r\n\r\n                   ..........Life is Random, So am I..........\r\n",
"\r\n\r\n                   ..........Life isn't about waiting for the storm to pass its about dancing in the rain..........\r\n",
"\r\n\r\n                   ..........Life isn't like a box of chocolates.Its more like a jar of jalapenos. What u do today, might burn your ass tomorrow..........\r\n",
"\r\n\r\n                   ..........Life was so much easier when clothes didn't match and boys had cooties..........\r\n",
"\r\n\r\n                   ..........Light travels faster than sound. That's why some people appear bright until you hear them speak..........\r\n",
"\r\n\r\n                   ..........Live it up, and Drink it down..........\r\n",
"\r\n\r\n                   ..........Live like theres no tomorrow laugh like you did when were young love like youve never been hurt..........\r\n",
"\r\n\r\n                   ..........Love is just a word until you find someone that gives it definition..........\r\n",
"\r\n\r\n                   ..........Love me or hate me, personally.... I couldn't care less..........\r\n",
"\r\n\r\n                   ..........Me? Crazy? Yeah, well you won't forget me..........\r\n",
"\r\n\r\n                   ..........Men are from earth. Women are from earth. Deal with it..........\r\n",
"\r\n\r\n                   ..........Middle age is when broadness of the mind and narrowness of the waist change places..........\r\n",
"\r\n\r\n                   ..........Mirrors don't lie, and thankfully for you they don't laugh..........\r\n",
"\r\n\r\n                   ..........Music screams the words we are afraid to speak..........\r\n",
"\r\n\r\n                   ..........My idea of housework is to sweep the room with a glance..........\r\n",
"\r\n\r\n                   ..........My imaginary friend thinks you have some serious mental issues..........\r\n",
"\r\n\r\n                   ..........My mind not only wanders, sometimes it leaves completely..........\r\n",
"\r\n\r\n                   ..........My naughty places are in need of attention..........\r\n",
"\r\n\r\n                   ..........Never argue with an idiot. They drag you down to their level and beat you with experience..........\r\n",
"\r\n\r\n                   ..........Never do anything you don't want to explain to the paramedics..........\r\n",
"\r\n\r\n                   ..........Never go to bed angry.. stay awake and plot your revenge..........\r\n",
"\r\n\r\n                   ..........Never lick a steak knife..........\r\n",
"\r\n\r\n                   ..........Never regret anything, because at one time...it was exactly what you wanted..........\r\n",
"\r\n\r\n                   ..........Never say anything that even remotely suggests that u think she's pregnant unless u see an actual baby emerging from her atm..........\r\n",
"\r\n\r\n                   ..........Never, under any circumstances, take a sleeping pill and a laxative on the same night..........\r\n",
"\r\n\r\n                   ..........Nice guys finish last...cuz we make our women cum FIRST..........\r\n",
"\r\n\r\n                   ..........No man has ever been shot while doing the dishes..........\r\n",
"\r\n\r\n                   ..........No, I wont go to hell. I've got a restraining order..........\r\n",
"\r\n\r\n                   ..........No, of course Im not being sarcastic..........\r\n",
"\r\n\r\n                   ..........Nobody cares if you can't dance well. Just get up and dance..........\r\n",
"\r\n\r\n                   ..........Not one shred of evidence supports the notion that life is serious..........\r\n",
"\r\n\r\n                   ..........Not the sharpest tool in the shed are ya..........\r\n",
"\r\n\r\n                   ..........NOTICE-Sexual Harassment in this area will NOT be reported, but it WILL be graded..........\r\n",
"\r\n\r\n                   ..........OK, so what's the speed of dark..........\r\n",
"\r\n\r\n                   ..........Okay, so how do I block you in real life..........\r\n",
"\r\n\r\n                   ..........OMG OMG OMG...wait.....I forgot..........\r\n",
"\r\n\r\n                   ..........On the other hand, you have different fingers..........\r\n",
"\r\n\r\n                   ..........One of a kind, You'll never find another like ME..........\r\n",
"\r\n\r\n                   ..........Opportunities always look bigger going than coming..........\r\n",
"\r\n\r\n                   ..........Out of my mind.. Back in 5 mins..........\r\n",
"\r\n\r\n                   ..........PATIENCE- Its important to wait til the perfect time to screw someone over..........\r\n",
"\r\n\r\n                   ..........People like you are the reason people like me need medication..........\r\n",
"\r\n\r\n                   ..........People who want to share their religious views with you almost never want you to share yours with them..........\r\n",
"\r\n\r\n                   ..........Please feel free to SHUT THE FUCK UP..........\r\n",
"\r\n\r\n                   ..........Please take a number and stick it up your ass..........\r\n",
"\r\n\r\n                   ..........Remember, half the people you know are below average..........\r\n",
"\r\n\r\n                   ..........Rest assured, no one gives a shit what you think..........\r\n",
"\r\n\r\n                   ..........Sex is Evil, Sex is a Sin, Sins are forgiven, so STICK IT IN..........\r\n",
"\r\n\r\n                   ..........Sex is not the answer. Sex is the question, YES is the answer..........\r\n",
"\r\n\r\n                   ..........Shhh I'm secretly frying your brain cells..........\r\n",
"\r\n\r\n                   ..........Side by side or miles apart Friends are forever close to your heart..........\r\n",
"\r\n\r\n                   ..........Some days all I want to be is a missing person..........\r\n",
"\r\n\r\n                   ..........Some people are alive ONLY because it's illegal to kill them..........\r\n",
"\r\n\r\n                   ..........Some people put up walls not to keep others out, but to see who cares enough to tear them down..........\r\n",
"\r\n\r\n                   ..........Someday Everything will all make perfect sense..........\r\n",
"\r\n\r\n                   ..........Someone who thinks logically provides nice contrast to the real world..........\r\n",
"\r\n\r\n                   ..........Sometimes the dreams that come true are the ones you never knew you had..........\r\n",
"\r\n\r\n                   ..........Sometimes we just have to accept that some people will stay in our hearts, even if we aren't in theirs..........\r\n",
"\r\n\r\n                   ..........Sometimes you just gotta say WHAT THE FUCK..........\r\n",
"\r\n\r\n                   ..........Strength is nothing more than how well you hide the pain..........\r\n",
"\r\n\r\n                   ..........Tell me, where is this BRIGHT side you speak of..........\r\n",
"\r\n\r\n                   ..........Thank you. We're all refreshed and challenged by your unique point of view..........\r\n",
"\r\n\r\n                   ..........The answer may not lie at the bottom of the bottle, but cant hurt to check..........\r\n",
"\r\n\r\n                   ..........The early bird may get the worm, but the second mouse gets the cheese in the trap..........\r\n",
"\r\n\r\n                   ..........The fact that no one understands you doesn't mean you're an artist..........\r\n",
"\r\n\r\n                   ..........The floggings will continue until the morale changes..........\r\n",
"\r\n\r\n                   ..........The most destructive force in the universe is gossip..........\r\n",
"\r\n\r\n                   ..........The most memorable people in life will be the friends who loved you when you weren't very lovable..........\r\n",
"\r\n\r\n                   ..........The one thing that unites us all,regardless of age, gender,religion, status or ethnicity, is that we ALL believe we are good drivers..........\r\n",
"\r\n\r\n                   ..........The only reason I'd kick you out of bed is to fuck you on the floor..........\r\n",
"\r\n\r\n                   ..........The past is like passing gas, it's best to pretend it never happened..........\r\n",
"\r\n\r\n                   ..........The police never think it's as funny as you do..........\r\n",
"\r\n\r\n                   ..........The problem with real life: There is no background music..........\r\n",
"\r\n\r\n                   ..........There is a nut loose on your keyboard..........\r\n",
"\r\n\r\n                   ..........There is a very fine line between hobby and mental illness..........\r\n",
"\r\n\r\n                   ..........There is always one more imbecile than you counted on..........\r\n",
"\r\n\r\n                   ..........They NEVER suspect the short one..........\r\n",
"\r\n\r\n                   ..........They told me it was only temporary.....they lied..........\r\n",
"\r\n\r\n                   ..........To be Old and Wise you must first be Young and Stupid..........\r\n",
"\r\n\r\n                   ..........True friends are never apart. Maybe in distance but never in heart..........\r\n",
"\r\n\r\n                   ..........Truely loving someone is wanting them to be happy in life, even if it doesn't involve you..........\r\n",
"\r\n\r\n                   ..........Update airDC ++ to the latest and improved version 2.80 File - >> Check for updates..........\r\n",
"\r\n\r\n                   ..........Update airDC ++ to the latest and improved version 2.80 File - >> Check for updates..........\r\n",
"\r\n\r\n                   ..........Update airDC ++ to the latest and improved version 2.80 File - >> Check for updates..........\r\n",
"\r\n\r\n                   ..........Update airDC ++ to the latest and improved version 2.80 File - >> Check for updates..........\r\n",
"\r\n\r\n                   ..........Update airDC ++ to the latest and improved version 2.80 File - >> Check for updates..........\r\n",
"\r\n\r\n                   ..........Uppdatera AirDC ++ till den senaste och förbättrad version 2.80 File - >> Sök efter uppdateringar..........\r\n",
"\r\n\r\n                   ..........Uppdatera AirDC ++ till den senaste och förbättrad version 2.80 File - >> Sök efter uppdateringar..........\r\n",
"\r\n\r\n                   ..........Uppdatera AirDC ++ till den senaste och förbättrad version 2.80 File - >> Sök efter uppdateringar..........\r\n",
"\r\n\r\n                   ..........Uppdatera AirDC ++ till den senaste och förbättrad version 2.80 File - >> Sök efter uppdateringar..........\r\n",
"\r\n\r\n                   ..........Uppdatera AirDC ++ till den senaste och förbättrad version 2.80 File - >> Sök efter uppdateringar..........\r\n",
"\r\n\r\n                   ..........Uppdatera AirDC ++ till den senaste och förbättrad version 2.80 File - >> Sök efter uppdateringar..........\r\n",
"\r\n\r\n                   ..........Uppdatera AirDC ++ till den senaste och förbättrad version 2.80 File - >> Sök efter uppdateringar..........\r\n",
"\r\n\r\n                   ..........Uppdatera AirDC ++ till den senaste och förbättrad version 2.80 File - >> Sök efter uppdateringar..........\r\n",
"\r\n\r\n                   ..........Uppdatera AirDC ++ till den senaste och förbättrad version 2.80 File - >> Sök efter uppdateringar..........\r\n",
"\r\n\r\n                   ..........Uppdatera AirDC ++ till den senaste och förbättrad version 2.80 File - >> Sök efter uppdateringar..........\r\n",
"\r\n\r\n                   ..........Update airDC ++ to the latest and improved version 2.80 File - >> Check for updates..........\r\n",
"\r\n\r\n                   ..........Update airDC ++ to the latest and improved version 2.80 File - >> Check for updates..........\r\n",
"\r\n\r\n                   ..........Update airDC ++ to the latest and improved version 2.80 File - >> Check for updates..........\r\n",
"\r\n\r\n                   ..........Update airDC ++ to the latest and improved version 2.80 File - >> Check for updates..........\r\n",
"\r\n\r\n                   ..........Update airDC ++ to the latest and improved version 2.80 File - >> Check for updates..........\r\n",
"\r\n\r\n                   ..........Update airDC ++ to the latest and improved version 2.80 File - >> Check for updates..........\r\n",
"\r\n\r\n                   ..........Update airDC ++ to the latest and improved version 2.80 File - >> Check for updates..........\r\n",
"\r\n\r\n                   ..........Uppdatera AirDC ++ till den senaste och förbättrad version 2.80 File - >> Sök efter uppdateringar..........\r\n",
"\r\n\r\n                   ..........Uppdatera AirDC ++ till den senaste och förbättrad version 2.80 File - >> Sök efter uppdateringar..........\r\n",
"\r\n\r\n                   ..........Uppdatera AirDC ++ till den senaste och förbättrad version 2.80 File - >> Sök efter uppdateringar..........\r\n",
"\r\n\r\n                   ..........Uppdatera AirDC ++ till den senaste och förbättrad version 2.80 File - >> Sök efter uppdateringar..........\r\n",
"\r\n\r\n                   ..........Uppdatera AirDC ++ till den senaste och förbättrad version 2.80 File - >> Sök efter uppdateringar..........\r\n",
"\r\n\r\n                   ..........Uppdatera AirDC ++ till den senaste och förbättrad version 2.80 File - >> Sök efter uppdateringar..........\r\n",
"\r\n\r\n                   ..........WARNING! Don't fuck with me. I fuck back..........\r\n",
"\r\n\r\n                   ..........WARNING! I consider it foreplay when you say BITE ME..........\r\n",
"\r\n\r\n                   ..........WARNING! I have an uncontrollable urge to lick you..........\r\n",
"\r\n\r\n                   ..........WARNING! WILL THROW nearest object when pissed..........\r\n",
"\r\n\r\n                   ..........Was today really necessary..........\r\n",
"\r\n\r\n                   ..........WELL! Arent we just a fucking ray of sunshine..........\r\n",
"\r\n\r\n                   ..........Well, aren't you just the extra crispy bucket of stupidity..........\r\n",
"\r\n\r\n                   ..........What's this thing called normal? It contagious? Dont touch me! I might catch it..........\r\n",
"\r\n\r\n                   ..........What am I? Flypaper for freaks..........\r\n",
"\r\n\r\n                   ..........What happens if you get scared half to death, twice..........\r\n",
"\r\n\r\n                   ..........What the hell is wrong with you? FOCUS..........\r\n",
"\r\n\r\n                   ..........When everything is coming your way, you're in the wrong lane..........\r\n",
"\r\n\r\n                   ..........When life gives you lemons, cram them up the butt of your enemies..........\r\n",
"\r\n\r\n                   ..........When you call us bitches, we look at eachother and laugh, cuz we knew that way before you did..........\r\n",
"\r\n\r\n                   ..........Who pissed in your corn flakes this morning..........\r\n",
"\r\n\r\n                   ..........Who said I went crazy, I could have been born with it..........\r\n",
"\r\n\r\n                   ..........Why do psychics have to ask you your name..........\r\n",
"\r\n\r\n                   ..........I know nothing about sex... Can you teach me?..........\r\n",
"\r\n\r\n                   ..........I have plenty of talent and vision. I just don.t give a fuck..........\r\n",
"\r\n\r\n                   ..........Damn the things I could do to you if you were in my presense...mmmmmm..........\r\n",
"\r\n\r\n                   ..........Growing old is mandatory; growing up is optional..........\r\n",
"\r\n\r\n                   ..........I have not failed. I have just found ten thousand ways that will not work..........\r\n",
"\r\n\r\n                   ..........I think all humans suffer from an Identity crisis at some point in their life... Makes me glad I'm a rabbit..........\r\n",
"\r\n\r\n                   ..........I Haven't Lost My Mind, It's Backed Up On Disk Somewhere..........\r\n",
"\r\n\r\n                   ..........GOT ENEMIES? Good, means you've stood up for something!..........\r\n",
"\r\n\r\n                   ..........I'm Smiling...that alone should scare you!..........\r\n",
"\r\n\r\n                   ..........Every girl has the right to be ugly, but you abused the privilege..........\r\n",
"\r\n\r\n                   ..........Why do psychics have to ask you your name..........\r\n",


}

local startTime
local delay = 60 * 180
local bot

hub.setlistener( "onStart", { },
	function()
		bot = hub.regbot{ nick = BotName, desc = "", client = function( bot, cmd ) return true end }
		startTime = os.time()
	end
)

hub.setlistener( "onTimer", { },
	function()
		if os.difftime( os.time( ), startTime ) >= delay then
			startTime = os.time()
            math.randomseed( os.time() )
			local index = math.random(1,#idlequestions)
			hub.broadcast( idlequestions[index], bot)
		end
	end
)

hub.debug( "** Loaded " .. scriptname .. " " .. scriptversion .. ".lua **" )